# -*- coding: utf-8 -*-
"""cognitve app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LTQwBy6bheXgwfLNQLUwEKzI28dOvEWf
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/CognitiveApp')
!pwd  # To verify your current directory

!pip install streamlit plotly numpy joblib scikit-learn spacy torch torchaudio whisper transformers librosa pandas textblob fastdtw scipy pyngrok

!pip install pyngrok
!brew install ngrok

!pip uninstall whisper
!pip install git+https://github.com/openai/whisper.git

!ngrok config add-authtoken 2t5xRPoMFuzy4iMynoHMNBjPUJ2_3dBm2iTa8UTB6MStym4xP

from pyngrok import ngrok
import os
import time

# --- Kill any existing ngrok tunnels ---
ngrok.kill()

# --- Step 2: Start the HTTP server for cognitive games on port 8000 ---
# This will serve cognitive_games.html and its related files.
# (Make sure cognitive_games.html is in the current directory.)
os.system("python -m http.server 8000 &")
time.sleep(5)  # Wait a few seconds for the server to start

# Use the local URL for cognitive games
# If you prefer to expose it via ngrok, you can uncomment the next two lines:
# games_tunnel = ngrok.connect(8000)
# cognitive_games_url = games_tunnel.public_url
cognitive_games_url = "http://localhost:8000/index.html"
print("Cognitive Games URL:", cognitive_games_url)

# Set an environment variable so your Streamlit app can pick up the cognitive games URL
os.environ["COGNITIVE_GAMES_URL"] = cognitive_games_url

# --- Step 3: Start your Streamlit app (demo.py) ---
os.system("streamlit run demo.py &")
time.sleep(5)  # Wait for Streamlit to start

# --- Step 4: Expose the Streamlit app via ngrok (port 8501) ---
streamlit_tunnel = ngrok.connect(8501)
streamlit_url = streamlit_tunnel.public_url
print("Streamlit Public URL:", streamlit_url)

# The script will print both URLs.

ngrok.kill()

from pyngrok import ngrok
import os
os.system("streamlit run demo.py &")
public_url = ngrok.connect(8501)  # Streamlit default port
print("Streamlit Public URL:", public_url)